* The issues
- On the one hand, generation of neighbors is logically the operation of State. On the other hand, it produces costs that need to be taken into account when forming nodes. In addition, forming a vector of nodes from a vector of states has an overhead.

- State logically pertains to the domain, while g pertains to search, so it does not make logical sense to put g together with State.

- We need to enable different kinds of node information, e.g. nodes that maintain both static and stored f-values.

- Storing a pointer to State with Node adds a level of indirection.

* Solution 1:
  - Note that, once the node is generated, we access State only to generate it's neighbors. The cost of indirection for this access is very small compared to the actual generation of the neighbots. Hence, we can afford storing the pointer to State with the node.
  - Assigning a state pointer is not a large overhead, so we'll put up with it for now.
  - We'll define a type for storing both a state and a cost of the transfer to this state from the parent.
