#ifndef EVENTS_HEADERS_H
#define EVENTS_HEADERS_H

/// \file
/// \brief Implementation of events generated by the search algorithms.
/// \author Meir Goldenberg

/// \namespace slb::ext::event
/// Events generated by the search algorithms.
namespace event {

using core::ui::EventBase;
using core::ui::EventType;
using core::ui::CurrentStyles;
using core::ui::VertexStyle;
using core::ui::EdgeStyle;
using core::util::Color;

#include "event_types.h"
#include "events.h"

} // namespace

#endif
