#ifndef EVENTS_HEADERS_H
#define EVENTS_HEADERS_H

/// \file
/// \brief Implementation of events generated by the search algorithms.
/// \author Meir Goldenberg

#include "event_types.h"
#include "events.h"

#endif
